import { nanoid } from 'nanoid'

export default {
  // wasmchi import signature: nanoid(): i32 is not what we want.
  // For now we demonstrate string argument import + host-side npm use.
  // We'll expose a function that logs an id generated by nanoid.
  js_log_id: (prefix) => {
    const id = nanoid()
    console.log(`${prefix}${id}`)
  },
}
